---
title: "Welcome"
format:
  html:
    page-layout: full
---

I'm Xingyu Zhong, an undergraduate student major in Mathematics at Beijing Institute of Technology (enrolled in 2022). My intrest ranges from mathematics (algebra mainly) to computer science (TCS / web / proof assistant mainly).

- [CV (zh)](/posts/cv/resume-zh.pdf)

## Talks

| Date | Title | Description | handouts | links |
| :---: | :---: | :---: | :---: | :---: |
| 2025/04/16 | Classification of Quardratic Forms over $\mathbb Q$ | 2025 spring *Algebraic Geometry* final presentation | [onsite (en)](/posts/20250416-ag-q-quadratic-form-classification/q-quadratic-form-classification.pdf) | |
| 2024/04/20 | 代数同构视角下的离散 Fourier 变换 | BIT & USTC undergraduate exchange for outstanding students major in mathematics | [onsite (zh)](/posts/20240420-utsc-dft/dft.pdf), [latest (zh)](https://blog.sun123zxy.top/posts/20240513-isodft/) | [news (zh)](https://math.bit.edu.cn/rcpy1/951c9035cf9849ce988e361861937b98.htm) |
| 2023/10/18 | 一元多项式的 Delta 判别式 | 2023 fall *Advanced Algebra II* course seminar | [onsite (zh)](/posts/20231018-aa2-discriminant/discriminant.pdf), [latest (zh)](https://blog.sun123zxy.top/posts/20231018-discriminant/) | |
| 2023/08/01 | A Convolution-Oriented FFT Tutorial | BITACMCLUB 2023 summer training | [onsite (zh)](/posts/20240801-bitacm-fft/fft.pdf), [suppliment on bit reverse operation (zh)](/posts/20240801-bitacm-fft/supplement-on-bit-reverse.pdf), [latest (zh)](https://blog.sun123zxy.top/posts/20230928-dft/) | [news (zh)](https://cs.bit.edu.cn/xyxw/619906a5c812458b9d22a663b74e0dce.htm) |
| 2023/05/18 | 空间填充曲线与集合势理论 | 2023 spring *Mathematical Analysis II* course seminar | [onsite (zh)](/posts/20230518-ma2-space-filling-curve/space-filling-curve.pdf), [latest (zh)](https://blog.sun123zxy.top/posts/20230519-hilbert/) | |
| 2023/04/23 | Wallis 公式、Stirling 公式与正态分布 | 2023 spring *Mathematical Analysis II* course seminar | [onsite (zh)](/posts/20230423-ma2-stirling.pdf), [latest (zh)](https://blog.sun123zxy.top/posts/20230423-stirling/) | |
| 2022/12/13 | 有限覆盖定理与实数理论 | 2022 fall *Mathematical Analysis I* course seminar | [latest (zh)](https://blog.sun123zxy.top/posts/20221213-cover/) | |