## Education

### Undergraduate

**2022/09 -- 2026/06 (ongoing) | Beijing Institute of Technology | Bachelor of Mathematics**

**Grades:** (by the end of 5th semester)

- **GPA:** 3.9 / 4.0 (93.6)
- **GPA Ranking:** 1 / 27
- **Overall Ranking:** 1 / 27
- Obtain 90+ scores in almost all core math courses
- Obtain 80+ scores in all courses

**Undergraduate Thesis:** (intention)

- Supervisor: Prof. Xun Xie (谢迅)
- Studying Area: algebraic groups, Lie algebras, Young tableaux

**Awards:**

:::{.list-table}

* - Date
  - Cycle
  - Award
  - Issued by

* - 2023/12
  - 2022--2023
  - Model Student <br> 优秀学生标兵
  - Bejing Institute of Technology

* - 2024/12
  - 2023--2024
  - Excellent Student <br> 三好学生
  - Bejing Institute of Technology
:::

**Scholarships:**

:::{.list-table}

* - Date
  - Cycle
  - Scholarship
  - Issued by

* - 2023/12
  - 2022--2023
  - National Scholarship <br> 国家奖学金
  - Ministry of Education, PRC

* - 2025/03
  - 2024--2025
  - Samsung Scholarship
  - Samsung Electronics China

* - 2022--2025
  - 1st--5th semester <br> (for 5 times)
  - First Class Scholarship
  - Bejing Institute of Technology
:::